### ISSUE TITLE
DROP TABLE...CASCADE does not clean up cstore files when run against a parent table

### ISSUE THREAD

**Issue by fbdiehlad** [citusdata/cstore_fdw#108]
I have a database configuration that includes cstore tables which inherit from a parent table.  When running DROP TABLE...CASCADE against the parent table, the underlying cstore files are not removed from disk.  

 #92 #3

**Comment by mtuncer** [comment]
That is similar to #92 as you marked. This is a more general indirect drop issue. cstore_fdw should find out dropped objects during sql drop event and remove any cstore_fdw resources mentioned there. It is planned in our upcoming v1.5 release.
