### ISSUE TITLE
change stripe_row_count and block_row_count on existing table

### ISSUE THREAD

**Issue by inkrement** [citusdata/cstore_fdw#127]
Is it possible to change these values on existing tables? Another questions would be how to set them accordingly. I read the manual, but would you have any recommendations for my specific setting? I have ~400GB RAM and the Dataset is about 100GB (300Mio. rows) so it would even fit in memory.

**Comment by mtuncer** [comment]
@inkrement these parameters are set in creation time. unfortunately you can't change them once a table is created.

stripe_row_count determines amount of memory needed when processing the table.  Higher stripe_row_count causes using more memory. Formula ``` (work_mem (in bytes)/ (3 x average_row_size (in bytes)))```  could be used for both uncompressed and compressed data. 

block_row_count may effect compression performance. higher block_row_count reduces number of blocks to be compressed, but increases individual block's compression time. It may have slight effect on memory consumption but we do not have a formula on this one.

**Comment by inkrement** [comment]
Thanks!
