### ISSUE TITLE
Dropping a database does not remove the cstore files 

### ISSUE THREAD

**Issue by jan-schulz-k24** [citusdata/cstore_fdw#129]
We have a mirror script which copies a database from production to a mirror (dump+restore to a temp database) and also copies over the cstore files (on the production host, copy over the cstore file for the DB to a temp directory with schema+table based names, rsync to mirror and move to the new ID based names in the cstore_fdw folder) . We then move the temp database over to the mirror database using:

```sql
DROP DATABASE IF EXISTS mirror;
ALTER DATABASE temp_db RENAME TO mirror;"
```

Unfortunately, this doesn't remove the cstore files from the old mirror database, resulting in leaked cstore files for each mirror run :-/

Script to reproduce:
```sql
CREATE DATABASE whatever;

\c whatever;

CREATE EXTENSION IF NOT EXISTS cstore_fdw;
CREATE SERVER cstore_server FOREIGN DATA WRAPPER cstore_fdw;

CREATE SCHEMA foo;

CREATE FOREIGN TABLE foo.bar (
  i INT
)
SERVER cstore_server;

-- show the IDs for the cstore files in the current database
SELECT
  (SELECT oid
   FROM pg_database
   WHERE datname = current_database()) AS dboid,
  ftrelid,
  nspname,
  relname
FROM pg_foreign_table
  JOIN pg_class ON pg_class.oid = ftrelid
  JOIN pg_namespace ON pg_namespace.oid = relnamespace;

\c postgres;

DROP DATABASE whatever;
```

Running it via `cat script | psql postgres` will show this:

```
$ cat script | psql postgres
[...]
 dboid  | ftrelid | nspname | relname 
--------+---------+---------+---------
 854324 |  854337 | foo     | bar
(1 row)
DROP DATABASE
$ ls -la /var/lib/postgresql/9.5/main/cstore_fdw/*/* |grep 854324
-rw------- 1 postgres postgres         0 Dez  8 11:50 /var/lib/postgresql/9.5/main/cstore_fdw/854324/854337
-rw------- 1 postgres postgres        26 Dez  8 11:50 /var/lib/postgresql/9.5/main/cstore_fdw/854324/854337.footer
```

-> The database is droped, but the cstore files for that database are still there.

**Comment by mtuncer** [comment]
Hey @jan-schulz-k24 

thanks for detailed reporting on the problem.  We will look into it.
