### ISSUE TITLE
truncate with tables compression?

### ISSUE THREAD

**Issue by skoschik** [citusdata/cstore_fdw#133]
I'm not able to truncate tables with compression enabled.   Postgres complains about it not being a table when i try.  c-store tables w/o compression truncate just fine.  I didn't see anything in the docs/tests regarding support for it, maybe I missed it though.   Wondering if there are any plans to support that feature in the future.  Thanks in advance

**Comment by mtuncer** [comment]
hello @skoschik 
thanks for reporting the issue.  I was not able to reproduce the problem locally. Could you please provide more information.
- did you change table name, or did any modification (add/drop column etc) on the table ?
- did you use a non-default schema ?
- what is the OS and PG version ?
