### ISSUE TITLE
Unused variable in cstore_reader.c 

### ISSUE THREAD

**Issue by sriharsha9992** [citusdata/cstore_fdw#135]
Hello,

While creating empty ColumnBlockSkipNode for missing columns, we have used the following code .

<pre>
for (blockIndex = 0; blockIndex < stripeBlockCount; blockIndex++)
{
		columnSkipList->rowCount = 0;
		columnSkipList->hasMinMax = false;
		columnSkipList->minimumValue = 0;
		columnSkipList->maximumValue = 0;
		columnSkipList->existsBlockOffset = 0;
		columnSkipList->valueBlockOffset = 0;
		columnSkipList->existsLength = 0;
		columnSkipList->valueLength = 0;
		columnSkipList->valueCompressionType = COMPRESSION_NONE;
}
</pre>

As you can see, we haven't used the loop variable blockIndex. Shouldn't the code be the following ??

<pre>
for (blockIndex = 0; blockIndex < stripeBlockCount; blockIndex++)
{
		columnSkipList[blockIndex].rowCount = 0;
		columnSkipList[blockIndex].hasMinMax = false;
		columnSkipList[blockIndex].minimumValue = 0;
		columnSkipList[blockIndex].maximumValue = 0;
		columnSkipList[blockIndex].existsBlockOffset = 0;
		columnSkipList[blockIndex].valueBlockOffset = 0;
		columnSkipList[blockIndex].existsLength = 0;
		columnSkipList[blockIndex].valueLength = 0;
		columnSkipList[blockIndex].valueCompressionType = COMPRESSION_NONE;
}
</pre>

**Comment by mtuncer** [comment]
hey @sriharsha9992 
thanks for reporting this. I will make sure it gets into next release.

**Comment by ozgune** [comment]
@mtuncer -- Does this point to a bug with our initialization logic?
