### ISSUE TITLE
Deserializing StripeSkipList for columns which are not projected

### ISSUE THREAD

**Issue by sriharsha9992** [citusdata/cstore_fdw#136]
Hello

We seem to deserialize StripeSkipList for columns which are not projected as well . I had a use case where I had 516 columns and only 16 columns had values. While projecting those 16 columns we get 50% to 100% increase in time while compared to the table with just those 16 columns.

I have uploaded a git diff fixing this issue. Kindly look into it.  
[cstore_large_col.diff.zip](https://github.com/citusdata/cstore_fdw/files/779100/cstore_large_col.diff.zip)

**Comment by mtuncer** [comment]
@sriharsha9992 thanks for reporting this, I will look into it.

**Comment by metdos** [comment]
@mtuncer #147 is merged, can we close this?
