### ISSUE TITLE
No such file or directory warning when attempting to drop database

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [citusdata/cstore_fdw#157]
Hi!

After upgrading to cstore version 1.6.0, I'm getting the following warning message when dropping a database:

> WARNING:  could not open directory "/var/lib/postgresql/9.6/main/cstore_fdw/497057": No such file or directory 

Where 497057 is an OID of the removed database.

Here are my platform details:
```
postgres=# select version();
                                                     version
-----------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
(1 row)

postgres=# show shared_preload_libraries ;
    shared_preload_libraries
--------------------------------
 pg_stat_statements, cstore_fdw
(1 row)

postgres=# select name, installed_version from pg_available_extensions where name = 'cstore_fdw';
    name    | installed_version
------------+-------------------
 cstore_fdw | 1.6
(1 row)
```
And steps to reproduce:
```
postgres=# create database tmp;
CREATE DATABASE
postgres=# select oid from pg_database where datname = 'tmp';
  oid
--------
 497057
(1 row)

postgres=# drop database tmp;
WARNING:  could not open directory "/var/lib/postgresql/9.6/main/cstore_fdw/497057": No such file or directory
DROP DATABASE
```

**Comment by mtuncer** [comment]
hi @kostiantyn-nemchenko 
thanks for the report. Although it is a harmless warning, I prepared a fix for that. It is available at [fix_warning](https://github.com/citusdata/cstore_fdw/tree/fix_warning) branch.  It will be available on [develop_v1x](https://github.com/citusdata/cstore_fdw/tree/develop_v1x) branch soon.

**Comment by kostiantyn-nemchenko** [comment]
@mtuncer ,  thanks for the feedback!
Already tested your fix on my side. No warning anymore.

**Comment by mtuncer** [comment]
merged into develop_v1x branch 
closing this
