### ISSUE TITLE
Can cstore_fdw extension to be used for  access to Oracle ?

### ISSUE THREAD

**Issue by MaDKoder369** [citusdata/cstore_fdw#164]
Can cstore_fdw extension to be used for  access to Oracle databases and move data from it? If yes, please provide example. Thanks in advance!

**Comment by pykello** [comment]
On Wed, Sep 27, 2017 at 2:36 AM, MaDKoder369 <notifications@github.com>
wrote:

> Can cstore_fdw extension to be used for access to Oracle databases and
> move data from it? If yes, please provide example. Thanks in advance!
>

There is now cstore_fdw specific solution for this. However, you might be
able to use orcale_fdw [1] to copy data from Orcale tables to any
PostgreSQL table (including cstore tables). All you need to do is (1)
Create an oracle_fdw table, (2) Create a matching cstore_fdw table, (3)
INSERT INTO cstore_table SELECT * FROM oracle_table.

[1] https://github.com/laurenz/oracle_fdw
