### ISSUE TITLE
Error installing cstore_fdw extension in Postgres 9.6.5

### ISSUE THREAD

**Issue by roteroj** [citusdata/cstore_fdw#166]
When trying to build cstore_fdw extension in Postgres 9.6.5 in a Linux Server  I'm getting the next error with make command:

$ PATH=/usr/pgsql-9.6/bin/:$PATH make
Makefile:39: /usr/pgsql-9.6/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
Makefile:46: *** PostgreSQL 9.3 or 9.4 or 9.5 or 9.6 or 10 is required to compile this extension.  Stop.

My server is a Distribución: RHEL 7.3 (Maipo). How I can install the missing libraries?

Thank in advance and best regards.

Rafa.

**Comment by mtuncer** [comment]
could you install devel package ?

```
yum install postgresql96-devel
```

**Comment by roteroj** [comment]
Hi Murat,

        Thank
you very much for your quick response. I've installed devel package and
I have been able to install the cstore_fdw extension and to start postgres
as well.

Thank you again for your help.

Best regards.

Rafael.







Rafael
Otero Lorenzo
Sistemas Centrales
C/ Caballero de Gracia 28-30 - 28013 Madrid
Tel. +34 915965474 915965544
rotero@cecabank.es
 




AVISO LEGAL
Este mensaje está dirigido únicamente a su destinatario y es confidencial.
Si lo ha recibido por error, Cecabank
le informa que su contenido es reservado y su lectura, copia y uso no está
autorizado. Cecabank
no garantiza la confidencialidad
de los mensajes transmitidos vía internet y se reserva el derecho a ejercer
las acciones legales que le correspondan contra todo tercero que acceda
de forma ilegítima al contenido de este mensaje y al de los ficheros contenidos
en el mismo. 
Por favor, considera tu
responsabilidad con el medio ambiente antes de imprimir este e-mail




De:      
 Murat Tuncer <notifications@github.com>
Para:      
 citusdata/cstore_fdw
<cstore_fdw@noreply.github.com>, 
cc:      
 roteroj <rotero@cecabank.es>,
Author <author@noreply.github.com>
Fecha:      
 03/11/2017 10:46
Asunto:    
   Re: [citusdata/cstore_fdw]
Error installing cstore_fdw extension in   Postgres 9.6.5 (#166)




could you install devel package ?
yum install postgresql96-devel

—
You are receiving this because you authored the thread.
Reply to this email directly, view
it on GitHub, or mute
the thread.
