### ISSUE TITLE
PostgreSQL 11 build error

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/cstore_fdw#187]
Hi,

cstore_fdw fails to build against PostgreSQL 11:

`make[1]: Entering directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/cstore_fdw/master/cstore_fdw-1.6.0'
Makefile:45: *** PostgreSQL 9.3 or 9.4 or 9.5 or 9.6 or 10 is required to compile this extension.  Stop.
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/cstore_fdw/master/cstore_fdw-1.6.0'
error: Bad exit status from /var/tmp/rpm-tmp.jSrBXf (%build)
`

**Comment by mtuncer** [comment]
hi @devrimgunduz thanks for the report. I am already aware of the issue.

I started working on it. build error is fixed in local branch but there is some testing failure I need to resolve.

**Comment by devrimgunduz** [comment]
Hi,
PostgreSQL 11 Beta 2 is already out, any updates on this?

Thanks!

Regards, Devrim

**Comment by devrimgunduz** [comment]
ping

**Comment by mtuncer** [comment]
@devrimgunduz see https://github.com/citusdata/cstore_fdw/releases/tag/v1.6.2

**Comment by mtuncer** [comment]
closing the issue since we have the support PG11, keeping it open will not make sense anymore
