### ISSUE TITLE
OOM death on SQL COPY

### ISSUE THREAD

**Issue by btubbs** [citusdata/cstore_fdw#19]
I just spent a couple days figuring out why my dataset kept failing on SQL COPY like this:

```
cstore_test=# COPY airlines_complete_local FROM '/home/vagrant/airlines_cleaned.csv' WITH (FORMAT csv, HEADER true);
The connection to the server was lost. Attempting reset: Failed.
!> 
!> 
```

Whenever that would happen, I'd end up with a non-empty cstore file created, but no .footer file, so the table wasn't queryable.

```
cstore_test=# select count(*) from airlines_cleaned;
ERROR:  could not open file "/var/lib/postgresql/9.3/main/airlines_cleaned.orc.footer" for reading: No such file or directory
HINT:  Try copying in data to the table.
```
I eventually tracked it down to the OOM killer.  It looks like the Postgres subprocess doing the import got zapped.

I was testing in a Vagrant box with 1GB of RAM.

The dataset is a CSV with 660 columns and 245269 rows.  It's mostly small integers, with a few text columns.  The CSV file size is 251MB (uncompressed).  I can't post it publicly but could send privately if you'd like to test.

I've successfully loaded in much larger datasets, but not with so many columns.

Ideally, this would just work.  But if there are fundamental constraints on how much memory it takes to import a wide table, it'd be nice to get some kind of memory usage warning from the extension itself instead just the cryptic loss of connection that you get when the OOM killer kicks in.  I probably won't be the last person to run into this, so if we can save others the debugging time, that'd be nice.

**Comment by mtuncer** [comment]
changes are committed into develop branch, available immediately

**Comment by pykello** [comment]
Merged into master. Closing.
