### ISSUE TITLE
/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory

### ISSUE THREAD

**Issue by InstanceOfMichael** [citusdata/cstore_fdw#209]
```
iom@forge:~/code/cstore_fdw$ PATH=/usr/local/pgsql/bin/:$PATH make
Makefile:38: /usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
Makefile:45: *** PostgreSQL 9.3 or 9.4 or 9.5 or 9.6 or 10 or 11 is required to compile this extension.  Stop.

iom@forge:~/code/cstore_fdw$ psql -V
psql (PostgreSQL) 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1)
```

**Comment by mtuncer** [comment]
following should solve your problem
```
sudo apt-get install postgresql-server-dev-all
sudo apt-get install postgresql-common
```

**Comment by phpsxg** [comment]
centos8 遇到这个问题应该怎么办

translated: What should I do if I encounter this problem

**Comment by smpawar** [comment]
@mtuncer I am getting same error in postgresql 14, will the fix be the same?

**Comment by mtuncer** [comment]
Hello @smpawar the latest supported PG version is 13. 

Please use citus extension for PG14 and above.
see the notice at https://github.com/citusdata/cstore_fdw#important-notice-columnar-storage-is-now-part-of-citus

**Comment by smpawar** [comment]
Thanks @mtuncer what would be the fix for version 11 ?
I am trying this command:
sudo yum install postgresql-server-11-dev-all

**Comment by mtuncer** [comment]
`sudo yum install postgresql11-devel` should help

**Comment by dberardo-com** [comment]
how to do this in fedora ? i mean using "microdnf", which package to install ?
