### ISSUE TITLE
Support for PostgreSQL 12

### ISSUE THREAD

**Issue by df7cb** [citusdata/cstore_fdw#212]
Trying to build cstore_fdw with 12beta1:
```
15:29:44 make[1]: Entering directory '/<<PKGBUILDDIR>>'
15:29:44 Makefile:45: *** PostgreSQL 9.3 or 9.4 or 9.5 or 9.6 or 10 or 11 is required to compile this extension.  Stop.
15:29:44 make[1]: Leaving directory '/<<PKGBUILDDIR>>'
```

IMHO it would be better to just ditch that check. If it doesn't compile, it doesn't compile, but if it compiles and passes the tests with the new version, I could just update the Debian package now, without having to poke upstream.

**Comment by serprex** [comment]
I'll spoil the surprise for you & let you know there are compile errors when compiling against version 12

**Comment by marcocitus** [comment]
Reopening to track PG12 support.

**Comment by serprex** [comment]
I started a branch yesterday, https://github.com/citusdata/cstore_fdw/commit/3b1269d465fd0e31350aa3d22dca9ab1e4108f7d but it's failing tests over files not existing & my guess is that I'm not correctly managing tuple slots

**Comment by devrimgunduz** [comment]
ping. v12 is due next week.

**Comment by devrimgunduz** [comment]
Thanks for the update.

**Comment by pabloa** [comment]
Hello, any news regarding postgres12 support?

**Comment by df7cb** [comment]
Debian is also waiting.

**Comment by kakoni** [comment]
Ping @mtuncer, @serprex Any updates on this?

**Comment by serprex** [comment]
@kakoni no, @DimCitus was going to look into it further, but he's been busy

**Comment by cpaelzer** [comment]
Hi,
Ubuntu also waits for this (just like Debian).
We wanted to have no postgresql-11 left in the upcoming LTS release 20.04 and right now cstore-fdw is one of the few holding it in.

Since the Feature Freeze date for 20.04 comes closer I wanted to ask again if @DimCitus or anyone else has made progress on this?

**Comment by df7cb** [comment]
Is Citusdata/Microsoft still supporting this extension or should I remove it from apt.postgresql.org and Debian?

**Comment by mtuncer** [comment]
Hi @df7cb could you allow us a week on this. I have already started looking into it. 

There is a compatibility issue with PG12 that required some work. I should have the fix sometime early next week.

**Comment by cpaelzer** [comment]
@mtuncer - thank you so much for your reply, glad to see a sign of life.

cstore-fdw is removed from Debian and Ubuntu for now. But I think @df7cb (for Debian) and myself (for Ubuntu) are more than happy to bring it back in as soon as it works. So let us know when the code is ready and if possible tag a new version with it right away so we can pick that.

The next related date should be the Ubuntu 20.04 Feature Freeze on 27th of February. Therefore if you'd really have it ready early next week it would be great to just slip back in before the freeze.

**Comment by mtuncer** [comment]
@df7cb @cpaelzer @devrimgunduz  @kakoni @pabloa  PG12 support related changes are merged to master and released under tag v1.7.0

**Comment by devrimgunduz** [comment]
Tthanks @mtuncer ! Pushed 1.7.0 to repos!

**Comment by df7cb** [comment]
Debian packages also updated, thanks!
