### ISSUE TITLE
Dropping column causes ERROR: cache lookup failed for type 0

### ISSUE THREAD

**Issue by moertel** [citusdata/cstore_fdw#217]
## Problem

When creating a foreign table and dropping one of its columns, certain select statements using the table alias will yield an `ERROR:  cache lookup failed for type 0`.

## Steps to reproduce

```sql
create foreign table t1 (id int, id2 int) server cstore_server options (compression 'pglz');
insert into t1 select 1, 2;
alter table t1 drop column id2;
select count(t1.*) from t1;
```

 * The statement `select count(*) from t1;` works flawlessly.
 * The statement `select count(t1.*) from t1;` works if no columns are dropped.

## Environment

 * `PostgreSQL 9.6.9 on x86_64-pc-linux-gnu (Debian 9.6.9-2.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`
 * `cstore_fdw` 1.6

I prepared a Gist with a Dockerfile that installs these versions and can reproduce the issue:
 * https://gist.github.com/moertel/08cc6a72b913990853f131bb4739f35c
 * 
    ```
    $ docker build --tag cstore-bug .
    $ docker run -p 5432:5432 -it cstore-bug
    $ psql -h 127.0.0.1 -p 5432 --user postgres postgres
    ```

**Comment by mtuncer** [comment]
Thanks for the detailed report I was able to reproduce it using your steps.

I will take this into next set of bugs we need to fix. I can't provide exact timing though.

**Comment by moertel** [comment]
Thanks for your quick reply! :) No worries about the timing; in case anyone else stumbles across this, I'm going with the following workaround:

Instead of this which causes the error:
```sql
select count(t1.*) from t1;
```
This works fine and produces the same result:
```sql
select count(1) filter(where t1.some_column is not null) from t1;
```

**Comment by moertel** [comment]
@mtuncer has this one ever made it onto your list of bugs to fix? Just curious if you could provide an update. :)

**Comment by mtuncer** [comment]
bug is fixed and released with v1.7.0

**Comment by moertel** [comment]
@mtuncer thanks for the fix! The new release doesn't seem to be available for download yet, is that on your radar? These install instructions still install `postgresql-9.6-cstore-fdw (1.6.2-1.pgdg90+1)` for me: https://gist.github.com/moertel/08cc6a72b913990853f131bb4739f35c#file-dockerfile-L9-L12

**Comment by mtuncer** [comment]
Hey @moertel ,  PostgreSQL folks are creating those packages. It should be available sometime later.

If you need it sooner, you can build from sources.
