### ISSUE TITLE
Support for table copies

### ISSUE THREAD

**Issue by jberkus** [citusdata/cstore_fdw#22]
Supporting incremental insert/update/deletes will take quite a bit of work.  However, another less difficult enhancement will make cstore_fdw 300% more useful right now, which would be support for *bulk* inserts, specifically:

     INSERT INTO cstore_table SELECT columns FROM regular_table;

As a shortcut, you could internally route this through the existing COPY code on the receiving end.  It would be deadly slow for single-row inserts, but then people doing single-row inserts into a cstore are mistaken anyway.

**Comment by pykello** [comment]
Merged into master. Closing.
