### ISSUE TITLE
Building troble

### ISSUE THREAD

**Issue by cptCarrotIronfoundersson** [citusdata/cstore_fdw#227]
I am not very strong in Linux.
At the building stage, I came to:

This path is typically the same as your PostgreSQL installation's bin/ directory path. For example:
PATH=/usr/local/pgsql/bin/:$PATH make sudo
 PATH=/usr/local/pgsql/bin/:$PATH make install

And here I do not really understand. My postgres is in a different path (/ etc / postgresql / 10) and there is no pg_config there (lies in usr / bin)

Could you explain to me how to install this package correctly, and what am I missing?

 **Forgive me for the stupid question, I will deal with Linux in the future.**

**Comment by mtuncer** [comment]
hi @cptCarrotIronfoundersson, I believe you solved the issue. Do you  still need assistance ?

**Comment by cptCarrotIronfoundersson** [comment]
> hi @cptCarrotIronfoundersson, I believe you solved the issue. Do you still need assistance ?

Thank you so much for asking!  ) I already figured it out)
