### ISSUE TITLE
Is cstore_fdw still supported by developers?

### ISSUE THREAD

**Issue by MusicMaker1337** [citusdata/cstore_fdw#236]
Hi everyone

I see that the last commit to the repository was way back in February, so I'm just wondering whether Cstore is still supported by the developers

**Comment by pykello** [comment]
Thanks for your interest. We are in process of planning for future of the columnar store project. You should hear from us in next couple of months.

**Comment by martin-loetzsch** [comment]
@pykello any updates on this?

**Comment by mtuncer** [comment]
https://github.com/citusdata/cstore_fdw#important-notice-columnar-storage-is-now-part-of-citus
