### ISSUE TITLE
Support for PostgreSQL15

### ISSUE THREAD

**Issue by jubinmytheen** [citusdata/cstore_fdw#252]
When we trying to configure the extension on our PostgreSQL 15 server, we are getting the below error.
```
Makefile:50: *** PostgreSQL 9.3 to 13 is required to compile this extension.  Stop.

```

Please check and do the needful.

**Comment by mtuncer** [comment]
columnar storage is now a part of citus extension.  Please see the comment https://github.com/citusdata/cstore_fdw#important-notice-columnar-storage-is-now-part-of-citus
