### ISSUE TITLE
fail to execute truncate and copy with column list

### ISSUE THREAD

**Issue by skykiker** [citusdata/cstore_fdw#30]
When I used Kettle's bulk load to copy data into a cstore table,it  failed.  
The SQL sended by The Kettle's bulk load is like the following.

postgres=# truncate cstb1;
ERROR:  "cstb1" is not a table

postgres=#  copy cstb1(id,name) from stdin with csv;
ERROR:  copy column list is not supported

How about  supporting the two SQLs in the future?

**Comment by viticq** [comment]
I simply commented out this block:
```
        if (columnNameList != NULL)
        {
              ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                                                errmsg("copy column list is not supported")));
      }
```
 in cstore_fdw.c and recompiled. 
This allows for processing to go further even if column list is given in the statement (I wonder why developers think this is an "error" and not a "warning"). 

V

**Comment by mtuncer** [comment]
truncate is merged into development version will be release with 1.4

**Comment by mtuncer** [comment]
verified copy column list works in v1.4. closing this issue
