### ISSUE TITLE
Query in subquery is slow

### ISSUE THREAD

**Issue by el2ro** [citusdata/cstore_fdw#37]
Cstore_fdw 1.1 on top of Postgresql 9.4 on Ubuntu 12.04 64bit.

Basic <query> from cstore fdw works pretty nicely but when adding another "SELECT * from ( <query> )t;" on top of that query, performance goes pretty bad. Is this expected behavior?

http://pgsql.privatepaste.com/8553019323

**Comment by mtuncer** [comment]
row count estimations are now merged to master and released with v1.3
