### ISSUE TITLE
Allow appending to existing cstore_fdw shards in CitusDB

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/cstore_fdw#46]
When I try to use the `master_append_table_to_shard` UDF for `cstore_fdw` shards, it gives an error:
```
ERROR:  cannot append to shardId 102108
DETAIL:  The underlying shard is not a regular table
```

**Comment by mtuncer** [comment]
@samay-sharma is this actionable on cstore side ? I think we need more info on this from citusdb ?

**Comment by samay-sharma** [comment]
Yes, I think this is more on the CitusDB side. We noted it here just so that we consider how that UDF should behave with columnar tables.

**Comment by sumedhpathak** [comment]
Closing this in favor of: https://github.com/citusdata/citus/issues/74
