### ISSUE TITLE
Concurrency issues with "INSERT INTO ... SELECT ..."

### ISSUE THREAD

**Issue by pykello** [citusdata/cstore_fdw#47]
Some users have observed that sometimes they get corrupt footer files when they try to concurrently use "INSERT INTO ... SELECT ...".

The related thread is: https://groups.google.com/forum/#!topic/cstore-users/THYfaSgPUHc

The scenario's which this can happen are:
* Concurrent INSERT and INSERT,
* Concurrent INSERT and COPY.

We should have protected two concurrent COPY commands from each-other by acquiring the proper locks, but we need to test for this.

Before taking action, we should make sure that the footer corruption is indeed happening because of concurrency issues. The footer file is usually small is and I expect the window for writing to it should be very small and chance of two concurrent bulk loads writing to it in the same time shouldn't be high. Irrespective of this, it seems that INSERT has some concurrency problems.

**Comment by mtuncer** [comment]
reproduction steps
1- create a customer_reviews foreign table to use amazon customer reviews 1998 and 1999
2- create a regular table review1998 with same schema as in customer reviews, fill it with 1998 data
3-create a regular table review1999 with same schema as in customer reviews, fill it with 1999 data
4-open up another psql session
5-issue following commands at the same time
  1->insert into customer_reviews select * from review1998;
  2->insert into customer_review select * from review1999;

6-issue select count query from either session,
7-see error message
ERROR:  could not unpack column store
DETAIL:  invalid stripe footer buffer

**Comment by pykello** [comment]
Merged into master. Closing.
