### ISSUE TITLE
PGLZ changed in 9.5-dev

### ISSUE THREAD

**Issue by pykello** [citusdata/cstore_fdw#48]
There have been some changes to PGLZ in 9.5-dev which breaks cstore_fdw. We need to make the corresponding changes in cstore_fdw.

http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=40bede5477bb5bce98ce9548841cb414634c26f7

**Comment by Bhuvanamitra** [comment]
When will be the release of cstore version which is modified according to PGLZ_9.5 ??

**Comment by sergunSpb** [comment]
Hello.
PostgreSQL 9.5 Alpha 2  has been released. What about this issue ?

**Comment by mtuncer** [comment]
It's going to be in next release (v1.4) of cstore.  However, it should get into development branch way sooner. (ie. some time in late august or early september)

**Comment by jmealo** [comment]
@mtuncer Any updates on this issue?

**Comment by mtuncer** [comment]
@marcocitus has recently made a patch for 9.5 at [feature-9.5_compatibility] (https://github.com/citusdata/cstore_fdw/tree/feature-9.5_compatibility) branch. Note that this will only work for postgresql 9.5+, it will not work for 9.3 or 9.4 releases.

cstore_fdw v1.4 will be compatible for all 9.3, 9.4, and 9.5 releases.

**Comment by sergunSpb** [comment]
Thanks a lot !

**Comment by onderkalaci** [comment]
@mtuncer is this closed now?

**Comment by mtuncer** [comment]
Changes are in develop branch. I will close this when we release it (in a day or two)

**Comment by mtuncer** [comment]
released with 1.4
