### ISSUE TITLE
Is there any automatic replication available

### ISSUE THREAD

**Issue by arunnairmr** [citusdata/cstore_fdw#54]
I want to know that Is there any automatic replication available. Currently we are copying data from csv file right? I just want to know that is there any option for updating data in citusDB from my postgresql database.

**Comment by pykello** [comment]
Just to clarify, cstore_fdw is an extension which works both on PostgreSQL and CitusDB, and it's not equal to CitusDB.

1. CitusDB provides automatic replication. See its [documentation](https://www.citusdata.com/docs) for more information. You could use CitusDB to auto-replicate cstore_fdw tables.
2. You can copy a PostgreSQL table into a non-distributed cstore table using "INSERT INTO cstore_table SELECT * FROM postgres_table". You currently cannot do this for distributed tables.
