### ISSUE TITLE
Support Hive 0.12 ORC files

### ISSUE THREAD

**Issue by Downchuck** [citusdata/cstore_fdw#56]
Support ORC files generated by Hive 0.12:
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+ORC

**Comment by Downchuck** [comment]
There is an ORC project written in C++ that could help once the implementation is complete:
https://github.com/hortonworks/orc

**Comment by pykello** [comment]
The design of cstore file layout is inspired by ORC, but it's not an implementation of ORC and it doesn't intend to support ORC files generated by Hive.
