### ISSUE TITLE
INSERT concurrency causes deadlock

### ISSUE THREAD

**Issue by netshade** [citusdata/cstore_fdw#57]
Using `cstore_fdw` to benchmark CitusDB and the `cstore_fdw` extension. During the `INSERT` phase of the benchmark, a CTE `INSERT` of the following form is performed:

```sql
WITH temp_table(id,project_id,time,value,count) AS (VALUES (...),(...)) INSERT INTO benchmark SELECT * FROM temp_table
```
_The rationale for using this awkward form of insertion due to being `cstore_fdw`'s lack of support for bulk insert of the form `INSERT INTO table VALUES (tuple_1),(tuple_2),(tuple_3)`_

When there is only one thread performing expressions of this type, the server accepts `INSERT`s as expected. When multiple threads are performing this same operation, the following error is printed in the CitusDB error log for all threads except the initial thread:

```
ERROR:  deadlock detected
DETAIL:  Process 2902 waits for ExclusiveLock on relation 16714 of database 16493; blocked by process 2900.
	Process 2900 waits for ExclusiveLock on relation 16714 of database 16493; blocked by process 2902.
```

Details regarding the machine where the error occurred:

```
[ec2-user@someip ~]$ /opt/citusdb/4.0/bin/psql --version
psql (PostgreSQL) 9.4.0
[ec2-user@someip ~]$ uname -a
Linux ip-someip 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@someip ~]$ cat /etc/system-release
Amazon Linux AMI release 2015.03
[ec2-user@someip ~]$ /opt/citusdb/4.0/bin/psql benchmark -c "\\d benchmark"
                 Foreign table "public.benchmark"
   Column   |       Type       |     Modifiers      | FDW Options 
------------+------------------+--------------------+-------------
 id         | integer          | not null           | 
 project_id | integer          | not null           | 
 time       | integer          | not null default 0 | 
 value      | double precision | not null default 0 | 
 count      | integer          | not null default 0 | 
Server: cstore_server
FDW Options: (compression 'pglz')
[ec2-user@someip cstore_fdw]$ git rev-parse HEAD
8943b85ae21fcccc9941192e45282aaa0e3e0755
```

Machine is an ec2-instance, `c3.2xlarge`.

**Comment by mtuncer** [comment]
Hello Chris
thanks for the detailed report. We will look into this. Could you help about reproduction steps ? Following information will be most useful
1. number of paralel insert sessions you were running.
2. some sample data.

We will try to reproduce the issue and post our findings and resolutions here.


As a side note
cstore_fdw insert feature is meant to be used for bulk row inserts.  Using it for single row inserts might cause some performance issues for read queries. If possible I suggest you to use an temporary regular table for single row inserts and  bulk insert them into cstore table periodically.

**Comment by pykello** [comment]
@netshade thanks for reporting this. I'll look into this soon.

**Comment by netshade** [comment]
@mtuncer Sure thing:

1. 4 threads were running, using a connection pool between them.
1. 
```sql
WITH temp_table(id,project_id,time,value,count) AS (
  VALUES (1,1,1432214440,10.0,1), 
         (2,1,1432214440, 24.323, 1), 
         ..REPEAT RANDOMLY GENERATED VALUES 1024 TIMES...
 ) INSERT INTO cstore_fdw_table SELECT * FROM temp_table
```

And yeah, that's exactly why I was doing bulk `INSERT` loads. While the batch sizes were pretty small, I wanted to test the effect of multiple concurrent loads in a `cstore_fdw` table; I'm not interested in single row inserts at all.

@pykello Awesome, thanks.

**Comment by mtuncer** [comment]
run the same query with 4 threads (no connection pooling) few times no problem is encountered.

**Comment by mtuncer** [comment]
I wrote a java client that has connection pooling (c3p0) with 4 threads. It issues the same command continuously. I let it run for a while but can not hit this issue.

I am stopping investigation

@netshade  If you still having this problem please let us know preferably with reproduction steps. So that we can diagnose it better.

**Comment by pykello** [comment]
I'm taking a brief look at this. Haven't found the main issue yet, but I've found a related issue.

When I put a breakpoint right after we grab the ```ExclusiveLock``` in ```CStoreBeginForeignModify``` and look at ```pg_locks``` at that point, I see two locks acquired on the cstore table: (1) ```ExclusiveLock```, (2) ```RowExclusiveLock```.

The 2nd lock is acquired automatically by PostgreSQL and I think it's the lock to grab for updates/inserts/deletes.

We added the ```ExclusiveLock``` so we don't have concurrency issues with COPY. I think what we should have done instead was to change the lock type in COPY to ```RowExclusiveLock```. This is the lock grabbed at PostgreSQL's copy.c too. We didn't need to add the ```ExclusiveLock``` to ```CStoreBeginForeignModify```.

I'll look more to find the issue @netshade reported, but I guess maybe following PostgreSQL's locking convention for inserts/updates/deletes may solve this problem and prevent other unexpected behaviors.

**Comment by pykello** [comment]
Steps for reproducing this issue:

* Create the benchmark table:
```SQL
CREATE FOREIGN TABLE benchmark (
    id int,
    project_id int,
    time int,
    value int,
    count int
)
SERVER cstore_server
OPTIONS (compression 'pglz');
```

* Create insert.sql as:
```SQL
WITH temp_table (id, project_id, time, value, count) AS(VALUES(1,2,3,4,5)) INSERT INTO benchmark SELECT * FROM temp_table;
```

* Run pgbench:

```
/opt/postgresql/9.4/bin/pgbench -c 16 -j 4 -f insert.sql -n -T 300 postgres
```

Then there's lots of deadlock reports:
```
Client 8 aborted in state 0: ERROR:  deadlock detected
DETAIL:  Process 11899 waits for ExclusiveLock on relation 16392 of database 13088; blocked by process 11909.
Process 11909 waits for ExclusiveLock on relation 16392 of database 13088; blocked by process 11899.
HINT:  See server log for query details.
```

I'm looking into this. Will keep this thread updated.

**Comment by pykello** [comment]
I think what happens is:

 1. Thread A acquires RowExclusive lock (postgres does this, not cstore),
 2. Thread B acquires RowExclusive lock (since RowExclusive lock doesn't conflict with RowExclusive locks. See [this](http://www.postgresql.org/docs/9.4/static/explicit-locking.html).
 3. Thread A tries to get Exclusive lock. Blocks, since thread B is holding RowExclusive lock which conflicts with Exclusive lock.
 4. Thread B tries to get Exclusive lock. Blocks, since thread A is holding RowExclusive.
 5. None of them can move further and deadlock happens.

I'll try to find a way to resolve this.

**Comment by pykello** [comment]
So, we need a lock type which:

* is self-conflicting, because we don't support concurrent updates yet.
* doesn't conflict with ROW EXCLUSIVE, so the deadlock doesn't happen.

I think what we want is a SHARE UPDATE EXCLUSIVE lock. I'll test this and create a pull request.

**Comment by mtuncer** [comment]
maybe we should also look at copy operation since it also uses exlusive lock

**Comment by samay-sharma** [comment]
@mtuncer : This looks like the issue we ran into with a customer. If there's no issue, can we open one specifically for COPY?
