### ISSUE TITLE
Alternatives to empty a table?

### ISSUE THREAD

**Issue by gabitoju** [citusdata/cstore_fdw#58]
I understand that DELETE and TRUNCATE are not implemented so I'd like to know if there's any way to empty a table.

I could do a DROP and then a CREATE but it's not very elegant.

Thanks

**Comment by mtuncer** [comment]
thats pretty much only way to empty a table at the moment. 
we will consider this when evaluating next set of improvements over cstore_fdw.

**Comment by mtuncer** [comment]
@gabitoju truncate support is released with 1.4
