### ISSUE TITLE
things to check if no performance improvement seen?

### ISSUE THREAD

**Issue by waypointsoftware** [citusdata/cstore_fdw#68]
I have loaded a cstore_fdw with about 10 columns of mostly int/date/varchar datatypes and running some fairly basic queries against it:
(The machine has very fast hardware, SSD's, 128GB ram, 40 core, 3ghz)

The table has about 16m rows in it and I ran ANALYZE _cstore after populating it with INSERT INTO()

SELECT zip, COUNT(*) FROM _cstore group by 1; --16 seconds
SELECT state, COUNT(DISTINCT phone1) FROM _cstore group by 1; --101 seconds
SELECT insertdate, COUNT(*) FROM _cstore WHERE email_domain = 'gmail.com' group by 1; --3 seconds

I kind of had the understanding (coming from the SQL Server column store world) that most queries against cstore tables would be nearly instant.

Are my queries not good judges of speed or could I have missed a setting somewhere that might explain why these queries run for so long (except the 3rd one)

**Comment by vnnw** [comment]
How did insert your data into cstore table? If the data were inserted into the table by sorting columns  that you will later use on where/group by clause, I think that cstore will shine then.

**Comment by mtuncer** [comment]
cstore operates as a foreign data wrapper to postgresql. Data is first fetched from cstore, then any grouping and counting is performed.

in the first query  (SELECT zip, COUNT() FROM _cstore group by 1), all values belonging to zip column is fetched from cstore, and grouping/counting performed by postgresql afterwards.

2nd query is similar, again all state and phone1 values are fetched, then grouping and distinct counting is performed by postgresql.

3rd query is different in the sense that it has filtering, cstore runs through field values and prunes out data blocks that do not have a match.

So general reasons for queries to take long are (1) having to return all values for selected columns, (2) group by/distincts on 16M rows.

I would like to investigate this issue further. Did you have chance to run those queries in regular posgresql tables  for comparison purposes ?

**Comment by mtuncer** [comment]
Regarding question about inserts.

cstore fdw uses multiple levels of grouping when inserting rows.

top level group is stripe. A stripe contains blocks, finally blocks have data blocks for columns.

in default settings, a stripe has 15 blocks, which has 10000 rows. Therefore a stripe contains 150K rows.

cstore reads stripe at a time when loading from disk. 

cstore also stores min/max values for each column at block and stripe level. Therefore, it is possible to skip stripes and disk blocks that does not contribute to query results when a filter is applied. If there is no filter, query becomes a sequential scan of the table.

cstore does not do any sorting during insertion. pre-sorting the input wrt most queried field would increase query performance since it will reduce disk reads and number of rows returned to postgresql.

**Comment by k1th** [comment]
Regarding moving data from cstore_fdw to PG:
We quite a big table with 30 million records both in cstore and in PG using these two queries:

```
select customerno, count(objectid) from object_columnar
where
donets >= '2015-07-01' and donets < '2015-08-01'
group by customerno

select customerno, count(objectid) from object
where
donets >= '2015-07-01' and donets < '2015-08-01'
group by customerno


select a, b, c, donets, d, e, f, g from object_columnar
where customerno = 'abdcdef' and donets >= '2015-07-01' and donets < '2015-08-01'
order by donets

select a, b, c, donets, d, e, f, g  from object
where customerno = 'abdcdef' and donets >= '2015-07-01' and donets < '2015-08-01'
order by donets
```

Using a regular select, the postgres table (which has an index on donets) is faster by a factor of 20.
Using the group by, the cstore query is faster by a factor of 50 or more.

I cannot explain this behaviour, as the group by happens within PG and the amount of data to be transferred from cstore to PG should be significantly bigger in the group by query and theorefore the query should be slower.

Why could this be the case?

Thanks for your help

**Comment by mtuncer** [comment]
One big difference in you group by queries is that you are fetching only 3
columns from the table.  This is the type of query that cstore will be
better at. (accessing small number of columns in the table)

The other query (order by) gets 9 fields. That may have significant affect
on total query time.



On Thu, Aug 27, 2015 at 4:57 PM, Chris Schwarzfischer <
notifications@github.com> wrote:

> Regarding moving data from cstore_fdw to PG:
> We quite a big table with 30 million records both in cstore and in PG
> using these two queries:
>
> select customerno, count(objectid) from object_columnar
> where
> donets >= '2015-07-01' and donets < '2015-08-01'
> group by customerno
>
> select customerno, count(objectid) from object
> where
> donets >= '2015-07-01' and donets < '2015-08-01'
> group by customerno
>
>
> select a, b, c, donets, d, e, f, g from object_columnar
> where customerno = 'abdcdef' and donets >= '2015-07-01' and donets < '2015-08-01'
> order by donets
>
> select a, b, c, donets, d, e, f, g  from object
> where customerno = 'abdcdef' and donets >= '2015-07-01' and donets < '2015-08-01'
> order by donets
>
> Using a regular select, the postgres table (which has an index on donets)
> is faster by a factor of 20.
> Using the group by, the cstore query is faster by a factor of 50 or more.
>
> I cannot explain this behaviour, as the group by happens within PG and the
> amount of data to be transferred from cstore to PG should be significantly
> bigger in the group by query and theorefore the query should be slower.
>
> Why could this be the case?
>
> Thanks for your help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citusdata/cstore_fdw/issues/68#issuecomment-135442077>
> .
>



-- 

*Murat Tuncer*Software Engineer | Citus Data
mtuncer@citusdata.com
