### ISSUE TITLE
code is issues

### ISSUE THREAD

**Issue by whxfly** [citusdata/cstore_fdw#69]
LoadStripeSkipList(FILE *tableFile, StripeMetadata *stripeMetadata,
				   StripeFooter *stripeFooter, uint32 columnCount,
				   Form_pg_attribute *attributeFormArray)
{
        ....
	/* table contains additional columns added after this stripe is created */
	for (columnIndex = stripeColumnCount; columnIndex < columnCount; columnIndex++)
	{
		ColumnBlockSkipNode *columnSkipList = NULL;
		uint32 blockIndex = 0;

		/* create empty ColumnBlockSkipNode for missing columns*/
		columnSkipList = palloc0(stripeBlockCount * sizeof(ColumnBlockSkipNode));

		for (blockIndex = 0; blockIndex < stripeBlockCount; blockIndex++)
		{
			columnSkipList->rowCount = 0;
			columnSkipList->hasMinMax = false;
			columnSkipList->minimumValue = 0;
			columnSkipList->maximumValue = 0;
			columnSkipList->existsBlockOffset = 0;
			columnSkipList->valueBlockOffset = 0;
			columnSkipList->existsLength = 0;
			columnSkipList->valueLength = 0;
			columnSkipList->valueCompressionType = COMPRESSION_NONE;
		}
		blockSkipNodeArray[columnIndex] = columnSkipList;
	}
       ...
}

**Comment by mtuncer** [comment]
Hi @whxfly could you elaborate the issue little bit ? I could not understand it from the comment.

thanks

**Comment by whxfly** [comment]
the code should ?
 
 for (blockIndex = 0; blockIndex < stripeBlockCount; blockIndex++)
    {
        columnSkipList[blockIndex].rowCount = 0;
        columnSkipList[blockIndex].hasMinMax = false;
        columnSkipList[blockIndex].minimumValue = 0;
        columnSkipList[blockIndex].maximumValue = 0;
        columnSkipList[blockIndex].existsBlockOffset = 0;
        columnSkipList[blockIndex].valueBlockOffset = 0;
        columnSkipList[blockIndex].existsLength = 0;
        columnSkipList[blockIndex].valueLength = 0;
        columnSkipList[blockIndex].valueCompressionType = COMPRESSION_NONE;
    }

**Comment by mtuncer** [comment]
that code portion is to support `alter table add column`. 
If a user adds a column after a cstore_fdw table is created, metadata for previously added columns do not have any values for the new column.  The code path you mention is to say we know nothing, about  values of new columns.

**Comment by mtuncer** [comment]
@whxfly  hope it answers your question. Is there anything else I can help you with ? otherwise I am going to close the issue.

thanks.
