### ISSUE TITLE
MacOS X - FATAL: could not access file “‘cstore_fdw’”: No such file or directory

### ISSUE THREAD

**Issue by kjedrzejewski** [citusdata/cstore_fdw#70]
On MacOSX I've installed cstore_fdw extension to PostgreSQL 9.3.5, and it looks there was no error in the process ("/usr/local/pgsql/bin/" is incorrect path, but files were copied where they should be, as pg_config is symlinked in the $PATH):

```
XXX:cstore_fdw kjedrzejewski$ sudo PATH=/usr/local/pgsql/bin/:$PATH make install
/bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/lib'
/bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension'
/bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension'
/usr/bin/install -c -m 755  cstore_fdw.so '/usr/local/Cellar/postgresql/9.3.5_1/lib/cstore_fdw.so'
/usr/bin/install -c -m 644 ./cstore_fdw.control '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/'
/usr/bin/install -c -m 644 ./cstore_fdw--1.3.sql ./cstore_fdw--1.2--1.3.sql ./cstore_fdw--1.1--1.2.sql ./cstore_fdw--1.0--1.1.sql  '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/'
XXX:cstore_fdw kjedrzejewski$ 
```

However, when I try to start Postgres, the extension cannot be loaded:
```
XXX:cstore_fdw kjedrzejewski$ pg_ctl -D /usr/local/var/postgres start
server starting
XXX:cstore_fdw kjedrzejewski$ FATAL:  could not access file "‘cstore_fdw’": No such file or directory
```

**Comment by mtuncer** [comment]
I think postgresql installation via brew is messing it up. cstore binaries
are copied to another folder.

Could you try changing Makefile so that pg_config refers to
/usr/local/pgsql/bin/pg_config ?


On Thu, Oct 8, 2015 at 1:48 PM, Krzysztof Jędrzejewski <
notifications@github.com> wrote:

> On MacOSX I've installed cstore_fdw extension to PostgreSQL 9.3.5, and it
> looks there was no error in the process ("/usr/local/pgsql/bin/" is
> incorrect path, but files were copied where they should be, as pg_config is
> symlinked in the $PATH):
>
> XXX:cstore_fdw kjedrzejewski$ sudo PATH=/usr/local/pgsql/bin/:$PATH make install
> /bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/lib'
> /bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension'
> /bin/sh /usr/local/Cellar/postgresql/9.3.5_1/lib/pgxs/src/makefiles/../../config/install-sh -c -d '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension'
> /usr/bin/install -c -m 755  cstore_fdw.so '/usr/local/Cellar/postgresql/9.3.5_1/lib/cstore_fdw.so'
> /usr/bin/install -c -m 644 ./cstore_fdw.control '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/'
> /usr/bin/install -c -m 644 ./cstore_fdw--1.3.sql ./cstore_fdw--1.2--1.3.sql ./cstore_fdw--1.1--1.2.sql ./cstore_fdw--1.0--1.1.sql  '/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/extension/'
> XXX:cstore_fdw kjedrzejewski$
>
> However, when I try to start Postgres, the extension cannot be loaded:
>
> XXX:cstore_fdw kjedrzejewski$ pg_ctl -D /usr/local/var/postgres start
> server starting
> XXX:cstore_fdw kjedrzejewski$ FATAL:  could not access file "‘cstore_fdw’": No such file or directory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citusdata/cstore_fdw/issues/70>.
>



-- 

*Murat Tuncer*Software Engineer | Citus Data
mtuncer@citusdata.com

**Comment by kjedrzejewski** [comment]
I've put `/usr/local/pgsql/bin` there thoughtlessly copying commands from the installation instruction. I've got only one installation of PostgreSQL in /usr/local/Cellar/postgresql/9.3.5_1/ . I have no `/usr/local/pgsql/` directory.

**Comment by mtuncer** [comment]
Do you still experience the problem ? Could you check "/usr/local/Cellar/postgresql/9.3.5_1/lib/" is there and cstore_fdw.so is in it ?

**Comment by kjedrzejewski** [comment]
It's there.

```
XXX:~ kjedrzejewski$ ll /usr/local/Cellar/postgresql/9.3.5_1/lib/c*.so
-r--r--r--  1 kjedrzejewski  admin  10052 17 paź  2014 /usr/local/Cellar/postgresql/9.3.5_1/lib/chkpass.so
-r--r--r--  1 kjedrzejewski  admin  14368 17 paź  2014 /usr/local/Cellar/postgresql/9.3.5_1/lib/citext.so
-r--r--r--  1 kjedrzejewski  admin  80116  7 paź 16:57 /usr/local/Cellar/postgresql/9.3.5_1/lib/cstore_fdw.so
-r--r--r--  1 kjedrzejewski  admin  40012 17 paź  2014 /usr/local/Cellar/postgresql/9.3.5_1/lib/cube.so
-r--r--r--  1 kjedrzejewski  admin  16424 17 paź  2014 /usr/local/Cellar/postgresql/9.3.5_1/lib/cyrillic_and_mic.so
XXX:~ kjedrzejewski$
```

**Comment by mtuncer** [comment]
what are the output of
"which pg_ctl"

and 
"which postgres"

Please also make sure that you have enough privileges to write inside folder "/usr/local/var/postgres" because cstore will try to create a folder there.

**Comment by kjedrzejewski** [comment]
```
XXX:~ kjedrzejewski$ which pg_ctl
/usr/local/bin/pg_ctl
XXX:~ kjedrzejewski$ ll /usr/local/bin/pg_ctl
lrwxr-xr-x  1 kjedrzejewski  admin  39 11 gru  2014 /usr/local/bin/pg_ctl -> ../Cellar/postgresql/9.3.5_1/bin/pg_ctl
XXX:~ kjedrzejewski$
```

```
XXX:~ kjedrzejewski$ which postgres
/usr/local/bin/postgres
XXX:~ kjedrzejewski$ ll /usr/local/bin/postgres
lrwxr-xr-x  1 kjedrzejewski  admin  41 11 gru  2014 /usr/local/bin/postgres -> ../Cellar/postgresql/9.3.5_1/bin/postgres
XXX:~ kjedrzejewski$
```

**Comment by mtuncer** [comment]
please check "/usr/local/var/postgres" folder make sure you can create folders beneath.

Have you upgraded to  "El Capitan" ? If so please see  [http://digitizor.com/2015/10/01/fix-homebrew-permissions-osx-el-capitan/] .

If you haven't upgraded please do not upgrade yet.  I am having some issues myself with el capitan.

**Comment by kjedrzejewski** [comment]
```
XXX:~ kjedrzejewski$ mkdir /usr/local/var/postgres/a
XXX:~ kjedrzejewski$ ll /usr/local/var/postgres/
total 112
drwx------  21 kjedrzejewski  admin    714  8 paź 17:10 .
drwxr-xr-x   5 kjedrzejewski  admin    170 17 kwi 23:11 ..
-rw-------   1 kjedrzejewski  admin      4 12 maj  2014 PG_VERSION
drwxr-xr-x   2 kjedrzejewski  admin     68  8 paź 17:10 a
drwx------  10 kjedrzejewski  admin    340 11 cze 23:49 base
drwx------  42 kjedrzejewski  admin   1428  8 paź 17:03 global
drwx------   3 kjedrzejewski  admin    102 17 paź  2014 pg_clog
-rw-------   1 kjedrzejewski  admin   4559 19 sie 21:04 pg_hba.conf
-rw-------   1 kjedrzejewski  admin   1636 12 maj  2014 pg_ident.conf
drwx------   4 kjedrzejewski  admin    136 17 paź  2014 pg_multixact
drwx------   3 kjedrzejewski  admin    102  8 paź 17:02 pg_notify
drwx------   2 kjedrzejewski  admin     68  8 paź 17:02 pg_stat
drwxr-xr-x   7 kjedrzejewski  admin    238  8 paź 17:10 pg_stat_tmp
drwx------   3 kjedrzejewski  admin    102 18 lip 21:08 pg_subtrans
drwxr-xr-x   2 kjedrzejewski  admin     68 12 gru  2014 pg_tblspc
drwxr-xr-x   2 kjedrzejewski  admin     68 12 gru  2014 pg_twophase
drwx------  11 kjedrzejewski  admin    374 18 lip 21:08 pg_xlog
-rw-------   1 kjedrzejewski  admin  20616  8 paź 17:02 postgresql.conf
-rw-------   1 kjedrzejewski  admin     81  8 paź 17:02 postmaster.opts
-rw-------   1 kjedrzejewski  admin     72  8 paź 17:02 postmaster.pid
-rw-r--r--   1 kjedrzejewski  admin   4116 12 maj  2014 server.log
XXX:~ kjedrzejewski$
```

I have already updated to El Capitan.

**Comment by jasonmp85** [comment]
@mtuncer — what issues are you having yourself with El Capitan? I had to do the homebrew hack, and had an issue with an important (Apple uses it for software update :worried:) Verisign certificate not being trusted (just manually marked it as trusted in Keychain), but other than that everything's been OK.

When I tried to repro this, I couldn't even _compile_ `cstore_fdw`, so I googled the error message, which led me to my [own post from last year](https://github.com/citusdata/cstore_fdw/issues/40#issuecomment-63553509).

After I ran that command, `cstore_fdw` compiled, installed, loaded and passed installcheck. This is on El Cap, LLVM 7.0.0, `cstore_fdw` master branch, building against PostgreSQL 9.3.9, installed using [this Homebrew tap](https://github.com/petere/homebrew-postgresql).

**Comment by mtuncer** [comment]
Yes exactly that one. protoc-c.h suddenly become not reachable.


On Fri, Oct 9, 2015 at 12:24 AM, Jason Petersen <notifications@github.com>
wrote:

> @mtuncer <https://github.com/mtuncer> — what issues are you having
> yourself with El Capitan? I had to do the homebrew hack, and had an issue
> with an important (Apple uses it for software update [image: :worried:])
> Verisign certificate not being trusted (just manually marked it as trusted
> in Keychain), but other than that everything's been OK.
>
> When I tried to repro this, I couldn't even *compile* cstore_fdw, so I
> googled the error message, which led me to my own post from last year
> <https://github.com/citusdata/cstore_fdw/issues/40#issuecomment-63553509>.
>
> After I ran that command, cstore_fdw compiled, installed, loaded and
> passed installcheck. This is on El Cap, LLVM 7.0.0, cstore_fdw master
> branch, building against PostgreSQL 9.3.9, installed using this Homebrew
> tap <https://github.com/petere/homebrew-postgresql>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citusdata/cstore_fdw/issues/70#issuecomment-146690155>
> .
>



-- 

*Murat Tuncer*Software Engineer | Citus Data
mtuncer@citusdata.com
