### ISSUE TITLE
Altering cstore table column data type might fail

### ISSUE THREAD

**Issue by holcapek** [citusdata/cstore_fdw#71]
Create cstore table, load a row to it:

    create foreign table foo (a int) server cstore_server;
    insert into foo select 1;
    select a from foo;

We get

     a 
    ---
     1
    (1 row)

Now change the column type, this time we are lucky:

    
    alter table foo alter column a type date;
    select a from foo;

And we get

         a      
    ------------
     2000-01-02
    (1 row)

Change the type again, this time we are not lucky:

    alter table foo alter column a type varchar(2);
    select a from foo;

And we get this

    ERROR:  could not open relation with OID 0

And one time, I even got

    ERROR:  invalid memory alloc request size 18446744072304459780

I guess it would be fine to prohibit altering column type to an incompatible one at a first step.

Thanks!

**Comment by mtuncer** [comment]
thanks for reporting, we will look into it for next release.

**Comment by hulponot** [comment]
also having trouble with type cast. Table with column a uuid:
`select * from cstore;`
                  a                   
--------------------------------------
 ec7477ee-add3-3401-a09b-e1a5c3d161fe

then change type:
`alter foreign table cstore alter a type varchar(36);`
No error on execution, but
`select * from cstore ;`
gives `ERROR:  insufficient data left in datum buffer`
When doing reverce (varchar->uuid, have no error, but some data is missing then)

**Comment by mtuncer** [comment]
I did some work on this. It looks like the safest issue is to allow only implicit coercions. 

Changing the column type from int to float would work, but the reverse operation would fail.

Any comments ?
