### ISSUE TITLE
cstore will not compile against 9.5

### ISSUE THREAD

**Issue by jberkus** [citusdata/cstore_fdw#74]
It is not currently possible to compile cstore against Postgres 9.5.

make_foreignscan requires new arguments:

cstore_fdw.c: In function 'CStoreGetForeignPlan':
cstore_fdw.c:1178:16: error: too few arguments to function 'make_foreignscan'
  foreignScan = make_foreignscan(targetList, scanClauses, baserel->relid,
                ^
In file included from cstore_fdw.c:40:0:
/usr/local/pgsql/include/server/optimizer/planmain.h:46:21: note: declared here
 extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
                     ^
<builtin>: recipe for target 'cstore_fdw.o' failed
make: *** [cstore_fdw.o] Error 1

**Comment by jberkus** [comment]
This is on the feature_9.5_compatibility branch, btw.

**Comment by marcocitus** [comment]
Looks like the make_foreignscan API changed in beta1. I updated the feature-9.5_compatibility branch to use the new API. (It would be really nice if there was some set of stable internal APIs that FDWs can call to retain compatibility)

**Comment by jberkus** [comment]
verified fixed in Master.
