### ISSUE TITLE
\stage command always issues one or two NOTICE: extension cstore_fdw already exists

### ISSUE THREAD

**Issue by awolfe-silversky** [citusdata/cstore_fdw#84]
Am I doing something wrong?  Is \stage always trying to issue a CREATE EXTENSION?

This noise is undesirable.  I don't want to have to set the session message level to prevent this.

**Comment by mtuncer** [comment]
Hey @awolfe-silversky, you are not doing anything wrong here. 
This behavior is coming from citusdb. It sends create extension/server commands before creating a new cstore shard at the worker node. There is pretty much nothing we can do at cstore side.

I hope it does not have adverse effect on your task.

**Comment by mtuncer** [comment]
closing
