### ISSUE TITLE
Postgres tries to open cstore_fdw files even when no FOREIGN SERVER is present

### ISSUE THREAD

**Issue by SharangP** [citusdata/cstore_fdw#85]
I installed cstore_fdw, created the extension, but had not yet created a foreign server.

When I attempted to create a foreign table using a **different** extension (tds_fdw), I got the following error:
`ERROR:  could not open file "...data/cstore_fdw/16385/2440525" for writing: No such file or directory`

This error disappeared after I created a cstore foreign server:
`create server cstore_server foreign data wrapper cstore_fdw;`

**Comment by mtuncer** [comment]
Hello @SharangP  thanks for reaching out to us. 

Unfortunately I was not able to reproduce the issue. create table command seemed to be routed to correct server (tested with current tds_fdw and file_fdw) using postgresql 9.5.1 and cstore_fdw 1.4)

Could you elaborate the issue a little bit more, including the postgresql version and OS ?

thanks

**Comment by SharangP** [comment]
Hi @mtuncer,

I am using postgresql 9.3.10 with cstore_fdw version 1.3 on Ubuntu 12.04

**Comment by SharangP** [comment]
@mtuncer unfortunately I dont think I'm going to have time to attempt to reproduce this anytime soon, so lets go ahead and close. At least there is a record in case someone else finds the issue.
