### ISSUE TITLE
DROP SCHEMA CASCADE doesn't delete cstore files

### ISSUE THREAD

**Issue by martin-loetzsch** [citusdata/cstore_fdw#92]
```
CREATE SCHEMA foo;

CREATE FOREIGN TABLE foo.bar (
  i INT
)
SERVER cstore_server;
```

This creates a `.cstore` and `.cstore.footer` file in the postgres directory, and `DROP FOREIGN TABLE foo.bar;` successfully deletes them again, as discussed in #3.

However, `DROP SCHEMA foo CASCADE;` does not delete these files, and it would be nice if it would. 

Our use case is data warehousing: To ensure an always-consistent set of data, the front-end runs queries against tables in schema `foo`, while ETL scripts progressively build up tables in schema `foo_next`. Once the ETL finishes and data is found to be consistent, we do this:

```
DO $$
BEGIN
  DROP SCHEMA foo CASCADE;
  ALTER SCHEMA foo_next RENAME TO foo;
END
$$;
```

(transactional DDL in Postgres is a super-amazing feature)

**Comment by mtuncer** [comment]
Hey @martin-loetzsch 
Thanks for reporting the issue we will look into it.
We will need to examine the behavior when this command is run within transaction.

**Comment by martin-loetzsch** [comment]
For the record, this is our current workaround:

```sql
-- replaces schema "schema" with "replace_with"
CREATE OR REPLACE FUNCTION util.replace_schema(schema TEXT, replace_with TEXT)
  RETURNS VOID AS $$
DECLARE foreign_table TEXT;
BEGIN
  FOR foreign_table IN
  SELECT foreign_table_name
  FROM information_schema.foreign_tables
  WHERE foreign_table_schema = schema
        AND foreign_server_name = 'cstore_server'
        AND foreign_server_catalog
            = (SELECT *
               FROM information_schema.information_schema_catalog_name) LOOP
    EXECUTE 'DROP FOREIGN TABLE "' || schema || '"."' || foreign_table || '"';
  END LOOP;

  EXECUTE 'DROP SCHEMA IF EXISTS ' || schema || ' CASCADE;';
  EXECUTE 'ALTER SCHEMA ' || replace_with || ' RENAME TO ' || schema || ';';
END;
$$ LANGUAGE 'plpgsql';

SELECT util.replace_schema('foo', 'foo_next');
```

And obviously, this would be nicer:

```sql
-- replaces schema "schema" with "replace_with"
CREATE OR REPLACE FUNCTION util.replace_schema(schema TEXT, replace_with TEXT)
  RETURNS VOID AS $$
BEGIN
  EXECUTE 'DROP SCHEMA IF EXISTS ' || schema || ' CASCADE;';
  EXECUTE 'ALTER SCHEMA ' || replace_with || ' RENAME TO ' || schema || ';';
END;
$$ LANGUAGE 'plpgsql';

SELECT util.replace_schema('foo', 'foo_next');
```

In terms of what to do in a transaction: In the best case, files would be deleted after a successful commit, but I'd be fine when the file is also gone when the transaction is rolled back (not leaking disk space is more important to us).

**Comment by martin-loetzsch** [comment]
Thanks at lot @mtuncer, highly appreciated
