### ISSUE TITLE
Make cstore_fdw postgresql 9.6 compatible

### ISSUE THREAD

**Issue by mtuncer** [citusdata/cstore_fdw#93]
There are few api changes in postgresql 9.6 regarding foreign tables.

cstore_fdw does not compile under 9.6devel. Changes detected so far are
1 - additional PathKey parameter in ```create_foreignscan_path()```
2 - Struct ```RelOptInfo``` is changed. ```List *reltargetlist``` is replaced by ```struct PathTarget *reltarget```
3 - function ```pull_var_clause()``` has now 2 parameters instead of 3
4 - can not locate ```BTREE_AM_OID``` which is now at ```catalog/pg_am.h```

Looks like items 1 and 2 are the ones with the most impact.

There are additional PG 9.6 changes that enable parallel scans, or in place aggregation These need to be considered for new feature development.

**Comment by wrschneider** [comment]
Does cstore support parallel workers yet?  I have been trying it out with 9.6 but the max_parallel_workers_per_gather setting seemed to have no impact on explain analyze or performance.

**Comment by mtuncer** [comment]
No, not yet. It is in our todo list though.
