### ISSUE TITLE
Query may return NULL columns if used in UNION ALL

### ISSUE THREAD

**Issue by mtuncer** [citusdata/cstore_fdw#95]
This issue is reported in cstore_fdw forum at https://groups.google.com/forum/#!topic/cstore-users/oqsWZHtlL74

Query 1:
 ```sql
(SELECT A*1 , B FROM TEST_UNION_1 LIMIT 10) UNION ALL (SELECT A*1 , B FROM TEST_UNION_2 LIMIT 10);
```
Query 2:
```sql 
(SELECT A*1 , B FROM TEST_UNION_1 ) UNION ALL (SELECT A*1 , B FROM TEST_UNION_2 );
```
Query 1 works fine but Query 2 returns NULL columns . This is because in "ColumnList" function has the following code snippet 
```C
if (neededColumn->varattno == columnIndex)
{	
	column = neededColumn;
 	break;
}
 ```
Query 1 --- varattno is 1,2 for a,b
Query 2 --- varattno is 141,2 for a,b

So CStore doesn't consider Column "a" and hence the NULL values.

**Comment by sriharsha9992** [comment]
Hi ,

   I have already fixed the issue . When the plan has APPEND state , PG includes Exprs in the targetColumnList. So , the 141 was actually a OPEXPR (int4mul) . To fix this , all we have to do is ,

REPLACE
List *targetColumnList =baserel->reltargetlist;

WITH
List *targetColumnList = pull_var_clause(baserel->reltargetlist, PVC_RECURSE_AGGREGATES, PVC_RECURSE_PLACEHOLDERS);

Regards,
Harsha
