### ISSUE TITLE
"INSERT INTO SELECT FROM" with regular and partitioned relations

### ISSUE THREAD

**Issue by trntv** [citusdata/cstore_fdw#98]
When trying to transfer data we are getting CitusDB standard error:
```
[XX000] ERROR: cannot plan queries that include both regular and partitioned relations
```
Is there any physical constraints not to allow users to transfer their data from regular staging table to partitioned cstore table?

**UPD**. If we i'll try to bypass this limitation by  creating distributed staging table we'll get this:
```
ERROR: cannot perform distributed planning for the given modifications
  Detail: Subqueries are not supported in distributed modifications.
```

**Comment by mtuncer** [comment]
Hey @trntv 

This is more of a Citus issue,  In fact there is an open issue https://github.com/citusdata/citus/issues/509 to track this.

cstore_fdw supports 2 ways to insert data. 1- copy, 2-insert into .. select.  The latter method is currently not supported in citus, so you are seeing this error.

Could you describe your scenario ?

**Comment by trntv** [comment]
Hey @mtuncer
Our scenario is to load data into distributed cstore table from staging table where data is inserted row by row (the way we can't write into cstore table). And, for now, i don't see any way to do it, except transferring data via csv files (copy to csv, copy from csv)

**Comment by mtuncer** [comment]
you can use command ```master_append_table_to_shard()``` to insert data into a cstore_fdw shard.

let's say your staging table's name is ```staging_table``` and your distributed cstore_fdw table's name is ```distributed_table```, distributed on ```partitionColumn``` using ```append``` method.

you first need to decide on a shard to insert into, if you want to insert into a new shard, you can also create an empty shard using ```master_create_empty_shard``` command.

Let's assume you want to insert into shard ```102500```.

run
```sql
select master_append_table_to_shard(102500, 'staging_table', 'localhost', 5432);
```

This command will connect to postgresql instance on host ```localhost``` running at port ```5432```, and copy the contents of table ```staging_table``` into shard ```102500```.

**Comment by trntv** [comment]
I've came up with this solution too. Thank you, @mtuncer.
